controller_joint_names: ['jaco2_joint_1','jaco2_joint_2','jaco2_joint_3','jaco2_joint_4','jaco2_joint_5','jaco2_joint_6']
# controller_joint_names: ['jaco2_joint_1','jaco2_joint_2','jaco2_joint_3','jaco2_joint_4,'jaco2_joint_5','jaco2_joint_6']
