marvin:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50

  # Position Controllers  ---------------------------------------
  linear_actuator_controller:
    type: position_controllers/JointPositionController
    joint: marvin_linear_actuator_joint
    pid: {p: 100.0, i: 0.01, d: 1.0}
  ptu_pan_controller:
    type: position_controllers/JointPositionController
    joint: ptu_pan
    pid: {p: 100.0, i: 0.01, d: 10.0}
  ptu_tilt_controller:
    type: position_controllers/JointPositionController
    joint: ptu_tilt
    pid: {p: 100.0, i: 0.01, d: 10.0}
