scan_filter_chain:
- name: shadows
  type: ScanShadowsFilter
  params:
    min_angle: 20
    max_angle: 160
    neighbors: 10
    window: 1
- name: range
  type: LaserScanRangeFilter
  params:
    lower_threshold: 0.5
    upper_threshold: 4.0 # range for hokuyo? # 9.0   # see marvin.gzebo.xacro gazebo/sensor/ray/range/max
