version: '2'
services:
  iki-robot-sim:
    image: 141.69.58.19:5000/iki/robot-sim:kinetic
    environment:
      ROS_IP: $ROS_IP
      ROS_MASTER_URI: $ROS_MASTER_URI
      WAIT_FOR_ROSCORE: 0
    network_mode: host
    #volumes:
    command: /bin/bash -c "
            tail -f /dev/null"
